# Generated by Django 2.1.5 on 2019-02-01 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('VoteWebCore', '0004_tb_votemulti_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_votemulti',
            name='vote_no',
        ),
    ]
