# Generated by Django 2.1.5 on 2019-02-03 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoteWebCore', '0005_remove_tb_votemulti_vote_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('text', models.CharField(max_length=300)),
                ('answers', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteWebCore.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tb_vote',
            name='vote_owner',
        ),
        migrations.RemoveField(
            model_name='tb_votediscret',
            name='vote_id',
        ),
        migrations.DeleteModel(
            name='TB_VoteLog',
        ),
        migrations.RemoveField(
            model_name='tb_votemulti',
            name='vote_id',
        ),
        migrations.DeleteModel(
            name='TB_VoteMulti_Answer',
        ),
        migrations.RemoveField(
            model_name='tb_votemulti_quest',
            name='quests_no',
        ),
        migrations.DeleteModel(
            name='TB_Vote',
        ),
        migrations.DeleteModel(
            name='TB_VoteDiscret',
        ),
        migrations.DeleteModel(
            name='TB_VoteMulti',
        ),
        migrations.DeleteModel(
            name='TB_VoteMulti_Quest',
        ),
        migrations.AddField(
            model_name='question',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteWebCore.Voting'),
        ),
    ]
