# Generated by Django 2.1.5 on 2019-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0009_auto_20190204_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
