# Generated by Django 2.1.5 on 2019-02-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0013_auto_20190206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='datetime_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
