# Generated by Django 2.1.5 on 2019-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0015_remove_voting_datetime_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='datetime_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
