# Generated by Django 2.1.5 on 2019-01-28 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_name', models.CharField(default='', max_length=32)),
                ('vote_type', models.IntegerField()),
                ('vote_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TB_VoteDiscret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_no', models.IntegerField()),
                ('vote_text_question', models.CharField(max_length=256)),
                ('vote_text_yes', models.CharField(max_length=16)),
                ('vote_text_no', models.CharField(max_length=16)),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteWebCore.TB_Vote')),
            ],
        ),
        migrations.CreateModel(
            name='TB_VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answ_user_id', models.IntegerField()),
                ('vote_id', models.IntegerField()),
                ('vote_no', models.IntegerField()),
                ('result_text', models.CharField(max_length=256)),
            ],
        ),
    ]
