# Generated by Django 2.1.5 on 2019-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('VoteWebCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_votelog',
            name='result_text',
        ),
        migrations.AddField(
            model_name='tb_votelog',
            name='answer_no',
            field=models.IntegerField(default=-1),
        ),
    ]
