# Generated by Django 2.1.5 on 2019-01-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_QuizDiscret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_no', models.IntegerField()),
                ('quiz_text_question', models.CharField(max_length=256)),
                ('quiz_text_yes', models.CharField(max_length=16)),
                ('quiz_text_no', models.CharField(max_length=16)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteWebCore.TB_Quiz')),
            ],
        ),
    ]
