# Generated by Django 2.1.5 on 2019-02-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
