# Generated by Django 2.1.4 on 2019-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0002_auto_20190211_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='role',
            field=models.IntegerField(choices=[(0, 'Avatar'), (1, 'Voting image'), (2, 'Question image')], default=0),
        ),
    ]
