# Generated by Django 2.1.4 on 2019-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0003_auto_20190211_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='role',
            field=models.IntegerField(choices=[(0, 'Avatar'), (1, 'Question image')], default=0),
        ),
    ]
