# Generated by Django 2.1.5 on 2019-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0003_tb_quizlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_quiz',
            name='quiz_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
