# Generated by Django 2.1.5 on 2019-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0003_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
