# Generated by Django 2.1.4 on 2019-02-04 10:22

import VoteWebCore.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0006_auto_20190203_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=VoteWebCore.models.JSONField(max_length=10000),
        ),
    ]
