# Generated by Django 2.1.5 on 2019-02-07 12:16

import VoteWebCore.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0006_auto_20190207_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.ImageField(null=True, upload_to=VoteWebCore.functions.generate_file_name),
        ),
    ]
