# Generated by Django 2.1.5 on 2019-02-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0007_image_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='owner',
        ),
    ]
