# Generated by Django 2.1.5 on 2019-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0008_auto_20190207_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
