# Generated by Django 2.1.5 on 2019-02-04 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VoteWebCore', '0008_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
