# Generated by Django 2.1.5 on 2019-02-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0009_image_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='status',
            new_name='banned',
        ),
    ]
