# Generated by Django 2.1.5 on 2019-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
