# Generated by Django 2.1.5 on 2019-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0011_auto_20190204_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='datetime_closed',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='voting',
            name='open_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
