# Generated by Django 2.1.5 on 2019-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0012_auto_20190209_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='type',
            field=models.IntegerField(choices=[(0, 'New voting'), (1, 'Vote'), (2, 'Added to favourite'), (3, 'Comment')], default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='role',
            field=models.IntegerField(choices=[(0, 'Avatar')], default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, 'Buttons'), (1, 'Radio inputs'), (2, 'Checkboxes')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Declined'), (2, 'Accepted')], default=0),
        ),
    ]
