# Generated by Django 2.1.5 on 2019-02-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0013_auto_20190209_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='owner',
            new_name='user',
        ),
    ]
