# Generated by Django 2.1.5 on 2019-02-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteWebCore', '0016_voting_datetime_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VoteWebCore.Voting'),
        ),
    ]
